import { useEffect, useMemo, useState } from 'react';
import { Briefcase, Calendar, FileText, FlaskConical, Globe, Image as ImageIcon, LayoutDashboard, LogOut, Puzzle, Search, Settings, Sparkles, Tags, Users } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { getCMSContent } from '../../data/cmsContent';
import { fetchAuditLogs } from '../../features/cms/audit/api';
import { fetchAnalyticsOverview } from '../../features/cms/analytics/api';
import { summarizeContent } from '../../features/cms/ai/api';
import { promoteContent } from '../../features/cms/environments/api';
import { fetchExperiments, startExperiment, stopExperiment } from '../../features/cms/experiments/api';
import { deleteMedia, fetchMedia, uploadMedia } from '../../features/cms/media/api';
import { createRule, fetchSegments, fetchVariants } from '../../features/cms/personalization/api';
import { fetchPlugins, activatePlugin, deactivatePlugin } from '../../features/cms/plugins/api';
import { searchContent } from '../../features/cms/search/api';
import { fetchSettings, updateSettings } from '../../features/cms/settings/api';
import { fetchUsers, inviteUser, updateUserRole, updateUserStatus } from '../../features/cms/users/api';
import type { UserRole, UserStatus } from '../../features/cms/users/types';
import { AdminDataTable, AdminFiltersBar, AdminFormSection, AdminShell, AdminSidebar, AdminStatsCards, AdminStatusBadge, AdminTopbar } from './admin/AdminUI';
import { EnvironmentBadge, ExperimentStatusBadge, PluginStatusBadge } from './admin/EnterprisePatterns';
import '../../styles/cms-premium.css';

type CMSSection = 'overview' | 'posts' | 'services' | 'events' | 'media' | 'taxonomies' | 'users' | 'settings' | 'headless' | 'environments' | 'personalization' | 'experiments' | 'search' | 'ai' | 'plugins';

const menuItems = [
  { id: 'overview', label: 'Dashboard', icon: LayoutDashboard }, { id: 'posts', label: 'Articles', icon: FileText }, { id: 'services', label: 'Services', icon: Briefcase }, { id: 'events', label: 'Events', icon: Calendar }, { id: 'media', label: 'Media', icon: ImageIcon }, { id: 'taxonomies', label: 'Taxonomies', icon: Tags }, { id: 'headless', label: 'Headless API', icon: Globe }, { id: 'environments', label: 'Environments', icon: Settings }, { id: 'personalization', label: 'Personalization', icon: Users }, { id: 'experiments', label: 'A/B Tests', icon: FlaskConical }, { id: 'search', label: 'Search', icon: Search }, { id: 'ai', label: 'AI Assistant', icon: Sparkles }, { id: 'plugins', label: 'Plugins', icon: Puzzle }, { id: 'users', label: 'Users', icon: Users }, { id: 'settings', label: 'Settings', icon: Settings },
] as const;

function CMSDashboard({ currentSection, onSectionChange }: { currentSection: CMSSection; onSectionChange: (section: CMSSection) => void }) {
  const { user, logout } = useAuth();
  const [search, setSearch] = useState('');
  const [media, setMedia] = useState<any[]>([]);
  const [settings, setSettings] = useState<any>({});
  const [teamUsers, setTeamUsers] = useState<any[]>([]);
  const [auditLogs, setAuditLogs] = useState<any[]>([]);
  const [inviteForm, setInviteForm] = useState({ name: '', email: '', role: 'viewer' as UserRole });
  const [analyticsOverview, setAnalyticsOverview] = useState({ published: 0, drafts: 0, scheduled: 0, uploads: 0, failedJobs: 0 });
  const [segments, setSegments] = useState<any[]>([]); const [variants, setVariants] = useState<any[]>([]);
  const [experiments, setExperiments] = useState<any[]>([]); const [plugins, setPlugins] = useState<any[]>([]);
  const [searchResults, setSearchResults] = useState<any[]>([]); const [aiOutput, setAiOutput] = useState('');

  useEffect(() => { fetchAnalyticsOverview().then(setAnalyticsOverview).catch(() => undefined); fetchAuditLogs().then(setAuditLogs).catch(() => undefined); fetchUsers().then((result) => setTeamUsers(result.items)).catch(() => undefined); fetchMedia().then(({ items }) => setMedia(items)).catch(() => undefined); fetchSettings().then((result) => setSettings(result.data?.item ?? {})).catch(() => undefined); fetchSegments().then(setSegments).catch(() => undefined); fetchVariants().then(setVariants).catch(() => undefined); fetchExperiments().then(setExperiments).catch(() => undefined); fetchPlugins().then(setPlugins).catch(() => undefined); }, []);

  const stats = useMemo(() => [{ label: 'Published', value: analyticsOverview.published }, { label: 'Drafts', value: analyticsOverview.drafts }, { label: 'Scheduled', value: analyticsOverview.scheduled }, { label: 'Failed jobs', value: analyticsOverview.failedJobs }], [analyticsOverview]);
  const posts = getCMSContent().filter((item) => item.type === 'posts' && item.title.toLowerCase().includes(search.toLowerCase()));

  return (<AdminShell sidebar={<AdminSidebar items={menuItems as any} activeId={currentSection} onChange={(id) => onSectionChange(id as CMSSection)} profileSlot={<div className="premium-subpanel px-3 py-2 text-xs text-slate-600">{user?.email ?? 'admin@smove.local'}</div>} footerSlot={<button className="flex w-full items-center gap-2 rounded-xl border border-rose-200 px-3 py-2 text-sm text-rose-600" onClick={async () => { await logout(); window.location.hash = 'login'; }}><LogOut size={16} />Déconnexion</button>} />} topbar={<AdminTopbar title={currentSection} subtitle="Plateforme headless enterprise" search={search} onSearch={setSearch} userSlot={<div className="premium-subpanel px-3 py-2 text-xs text-slate-600">{user?.name ?? 'Admin'}</div>} />}> 
      {currentSection === 'overview' && <div className="space-y-4"><AdminStatsCards stats={stats} /><AdminDataTable columns={['Action', 'Entity', 'Date']} rows={auditLogs.map((entry) => <tr key={entry.id}><td className="px-4 py-3">{entry.action}</td><td className="px-4 py-3">{entry.entityType}</td><td className="px-4 py-3 text-xs">{new Date(entry.createdAt).toLocaleString()}</td></tr>)} /></div>}
      {currentSection === 'headless' && <AdminDataTable columns={['Endpoint', 'Exposure']} rows={['/api/v1/public/posts','/api/v1/public/services','/api/v1/public/projects','/api/v1/public/events','/api/v1/public/taxonomies','/api/v1/public/brand'].map((path) => <tr key={path}><td className="px-4 py-3 font-mono text-xs">{path}</td><td className="px-4 py-3"><span className="text-emerald-600">Published-only</span></td></tr>)} />}
      {currentSection === 'environments' && <AdminFormSection title="Promotion panel" helper="Visibilité claire draft/staging/production"><div className="flex items-center gap-2"><EnvironmentBadge environment="draft" active /><EnvironmentBadge environment="staging" active={false} /><EnvironmentBadge environment="production" active={false} /></div><button className="premium-btn premium-btn-primary px-3 py-2 text-sm text-white" onClick={async () => { await promoteContent('post', posts[0]?.id, 'draft', 'staging'); toast.success('Promotion draft → staging effectuée'); }}>Promouvoir le 1er post en staging</button></AdminFormSection>}
      {currentSection === 'personalization' && <div className="space-y-3"><AdminDataTable columns={['Segment', 'Priority']} rows={segments.map((segment) => <tr key={segment._id}><td className="px-4 py-3">{segment.name}</td><td className="px-4 py-3">{segment.priority}</td></tr>)} /><AdminDataTable columns={['Variant', 'Type']} rows={variants.map((variant) => <tr key={variant._id}><td className="px-4 py-3">{variant.label}</td><td className="px-4 py-3">{variant.contentType}</td></tr>)} /><button className="rounded-xl border border-slate-300 px-3 py-2 text-sm" onClick={async () => { if (!segments[0] || !variants[0]) return; await createRule({ segmentId: segments[0]._id, contentType: variants[0].contentType, contentId: variants[0].contentId, variantId: variants[0]._id, priority: 1 }); toast.success('Règle de personnalisation créée'); }}>Créer une règle</button></div>}
      {currentSection === 'experiments' && <AdminDataTable columns={['Nom', 'Status', 'Split', 'Actions']} rows={experiments.map((exp) => <tr key={exp._id}><td className="px-4 py-3">{exp.name}</td><td className="px-4 py-3"><ExperimentStatusBadge status={exp.status} /></td><td className="px-4 py-3">{(exp.split ?? []).join(' / ')}</td><td className="px-4 py-3"><div className="flex gap-2"><button className="premium-btn px-2 py-1 text-xs" onClick={async () => { await startExperiment(exp._id); setExperiments(await fetchExperiments()); }}>Start</button><button className="premium-btn px-2 py-1 text-xs" onClick={async () => { await stopExperiment(exp._id); setExperiments(await fetchExperiments()); }}>Stop</button></div></td></tr>)} />}
      {currentSection === 'search' && <AdminFormSection title="Recherche cross-content"><input className="w-full rounded-xl border border-slate-200 p-2.5 text-sm" placeholder="Rechercher posts/services/projects/events" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="premium-btn premium-btn-primary px-3 py-2 text-sm text-white" onClick={async () => setSearchResults(await searchContent(search))}>Lancer</button><AdminDataTable columns={['Type', 'Titre', 'Score']} rows={searchResults.map((row, idx) => <tr key={`${row.type}-${idx}`}><td className="px-4 py-3">{row.type}</td><td className="px-4 py-3">{row.item?.title}</td><td className="px-4 py-3">{row.score}</td></tr>)} /></AdminFormSection>}
      {currentSection === 'ai' && <AdminFormSection title="AI assistant" helper="Toutes les suggestions nécessitent une validation manuelle."><textarea className="min-h-[120px] w-full rounded-xl border border-slate-200 p-2.5 text-sm" value={aiOutput} onChange={(e) => setAiOutput(e.target.value)} /><button className="premium-btn premium-btn-primary px-3 py-2 text-sm text-white" onClick={async () => { const result = await summarizeContent(aiOutput); setAiOutput(result?.summary ?? ''); }}>Proposer un résumé</button></AdminFormSection>}
      {currentSection === 'plugins' && <AdminDataTable columns={['Plugin', 'Version', 'Status', 'Actions']} rows={plugins.map((plugin) => <tr key={plugin.key}><td className="px-4 py-3">{plugin.name}</td><td className="px-4 py-3">{plugin.version}</td><td className="px-4 py-3"><PluginStatusBadge status={plugin.status} /></td><td className="px-4 py-3"><div className="flex gap-2"><button className="premium-btn px-2 py-1 text-xs" onClick={async () => { await activatePlugin(plugin.key); setPlugins(await fetchPlugins()); }}>Activer</button><button className="premium-btn px-2 py-1 text-xs" onClick={async () => { await deactivatePlugin(plugin.key); setPlugins(await fetchPlugins()); }}>Désactiver</button></div></td></tr>)} />}
      {currentSection === 'posts' && <AdminDataTable columns={['Title', 'Slug', 'Status']} rows={posts.map((post) => <tr key={post.id}><td className="px-4 py-3">{post.title}</td><td className="px-4 py-3">{post.slug}</td><td className="px-4 py-3"><AdminStatusBadge status={post.status} /></td></tr>)} />}
      {currentSection === 'users' && <div className="space-y-4"><AdminFormSection title="Inviter un utilisateur"><div className="grid gap-2 md:grid-cols-4"><input className="rounded-xl border border-slate-200 p-2.5 text-sm" placeholder="Nom" value={inviteForm.name} onChange={(e) => setInviteForm((v) => ({ ...v, name: e.target.value }))} /><input className="rounded-xl border border-slate-200 p-2.5 text-sm" placeholder="Email" value={inviteForm.email} onChange={(e) => setInviteForm((v) => ({ ...v, email: e.target.value }))} /><select className="rounded-xl border border-slate-200 p-2.5 text-sm" value={inviteForm.role} onChange={(e) => setInviteForm((v) => ({ ...v, role: e.target.value as UserRole }))}><option value="viewer">viewer</option><option value="author">author</option><option value="editor">editor</option><option value="admin">admin</option></select><button className="premium-btn premium-btn-primary px-3 py-2 text-sm text-white" onClick={async () => { await inviteUser(inviteForm); toast.success('Invitation envoyée'); setInviteForm({ name: '', email: '', role: 'viewer' }); const data = await fetchUsers(); setTeamUsers(data.items); }}>Inviter</button></div></AdminFormSection><AdminDataTable columns={['Nom', 'Email', 'Role', 'Status', 'Actions']} rows={teamUsers.map((member) => <tr key={member.id}><td className="px-4 py-3">{member.name}</td><td className="px-4 py-3">{member.email}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{member.role}</span></td><td className="px-4 py-3"><AdminStatusBadge status={member.status} /></td><td className="px-4 py-3"><div className="flex gap-2"><select value={member.role} className="premium-btn px-2 py-1 text-xs" onChange={async (e) => { await updateUserRole(member.id, e.target.value as UserRole); const data = await fetchUsers(); setTeamUsers(data.items); }}><option value="viewer">viewer</option><option value="author">author</option><option value="editor">editor</option><option value="admin">admin</option></select><select value={member.status} className="premium-btn px-2 py-1 text-xs" onChange={async (e) => { await updateUserStatus(member.id, e.target.value as UserStatus); const data = await fetchUsers(); setTeamUsers(data.items); }}><option value="active">active</option><option value="inactive">inactive</option><option value="invited">invited</option></select></div></td></tr>)} /></div>}
      {currentSection === 'media' && <div className="space-y-3"><AdminFiltersBar><label className="cursor-pointer rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700">Upload<input type="file" accept="image/*" className="hidden" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; await uploadMedia({ file }); toast.success('Média importé'); const result = await fetchMedia(); setMedia(result.items); }} /></label></AdminFiltersBar><AdminDataTable columns={['Nom', 'URL', 'Actions']} rows={media.filter((m) => m.originalName.toLowerCase().includes(search.toLowerCase())).map((file) => <tr key={file.id}><td className="px-4 py-3">{file.originalName}</td><td className="px-4 py-3 text-xs">{file.url}</td><td className="px-4 py-3"><button className="premium-btn px-2 py-1 text-xs text-rose-600" onClick={async () => { await deleteMedia(file.id); const result = await fetchMedia(); setMedia(result.items); }}>Supprimer</button></td></tr>)} /></div>}
      {currentSection === 'settings' && <AdminFormSection title="Settings"><div className="grid gap-3 md:grid-cols-2"><input className="rounded-xl border border-slate-200 p-2.5 text-sm" value={settings.heroVideoUrl || ''} onChange={(e) => setSettings((prev: any) => ({ ...prev, heroVideoUrl: e.target.value }))} /><input className="rounded-xl border border-slate-200 p-2.5 text-sm" value={settings.textLogo || ''} onChange={(e) => setSettings((prev: any) => ({ ...prev, textLogo: e.target.value }))} /></div><button className="premium-btn premium-btn-primary px-3 py-2 text-sm text-white" onClick={async () => { await updateSettings({ heroVideoUrl: settings.heroVideoUrl, textLogo: settings.textLogo }); toast.success('Paramètres sauvegardés.'); }}>Sauvegarder</button></AdminFormSection>}
    </AdminShell>);
}

export default CMSDashboard;
